import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('arpenspResult')
export class ArpenspResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @attribute()
    public ASpouseName: string;

    @IsNotEmpty()
    @attribute()
    public bookNumber: string;

    @IsNotEmpty()
    @attribute()
    public bookType: string;

    @IsNotEmpty()
    @attribute()
    public CNSNumber: string;

    @IsNotEmpty()
    @attribute()
    public collection: string;

    @IsNotEmpty()
    @attribute()
    public entryDate: string;

    @IsNotEmpty()
    @attribute()
    public matrcula: string;

    @IsNotEmpty()
    @attribute()
    public newSpouseName: string;

    @IsNotEmpty()
    @attribute()
    public page: string;
    
    @IsNotEmpty()
    @attribute()
    public registerNumber: string;

    @IsNotEmpty()
    @attribute()
    public registrationDate: string;

    @IsNotEmpty()
    @attribute()
    public registryOffice: string;

    @IsNotEmpty()
    @attribute()
    public spouseName: string;

    @IsNotEmpty()
    @attribute()
    public uF: string;

    @IsNotEmpty()
    @attribute()
    public weddingDate: string;

    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}