import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('cadespResult')
export class CadespResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @attribute()
    public ei: string;

    @IsNotEmpty()
    @attribute()
    public cnpj: string;

    @IsNotEmpty()
    @attribute()
    public businessName: string;

    @IsNotEmpty()
    @attribute()
    public drt: string;

    @IsNotEmpty()
    @attribute()
    public situation: string;

    @IsNotEmpty()
    @attribute()
    public dateRegistration: string;

    @IsNotEmpty()
    @attribute()
    public stateRegime: string;

    @IsNotEmpty()
    @attribute()
    public fiscalPoint: string;

    @IsNotEmpty()
    @attribute()
    public fancyName: string;

    @IsNotEmpty()
    @attribute()
    public nire: string;

    @IsNotEmpty()
    @attribute()
    public taxOccurrence: string;

    @IsNotEmpty()
    @attribute()
    public unitType: string;

    @IsNotEmpty()
    @attribute()
    public waysOfActing: string;
      
    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}