import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty, IsOptional } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('cagedResult')
export class CagedResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public company: {
        socialReason: string,
        address: {
            street: string,
            neighborhood: string,
            municipality: string,
            state: string,
            cep: string
        },
        contact: {
            name: string,
            cpf: string,
            ddd: string,
            phoneNumber: string,
            email: string,
            branch: string
        },
        infos: {
            economicActivity: string,
            branches: string,
            admissions: string,
            links: string,
            shutdowns: string
        }
    };

    @IsNotEmpty()
    @attribute()
    public personal: {
        pis: string,
        ctps: string,
        pisSituation: string,
        educationDegree: string,
        deficiency: string,
        nationality: string,
        gender: string,
        birthday: string,
        color: string,
        cagedWorkTime: string,
        raisWorkTime: string,
        works: {
            company: string,
            cnpj: string,
            start: string,
            end: string,
            situation: string
        }[]
    };
}