import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty, IsOptional } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('detranResult')
export class DetranResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;

    @IsNotEmpty()
    @attribute()
    public renach: string;

    @IsNotEmpty()
    @attribute()
    public category: string;

    @IsNotEmpty()
    @attribute()
    public date: string;

    @IsNotEmpty()
    @attribute()
    public name: string;

    @IsNotEmpty()
    @attribute()
    public fatherName: string;

    @IsNotEmpty()
    @attribute()
    public motherName: string;

    @IsNotEmpty()
    @attribute()
    public registry: string;

    @IsNotEmpty()
    @attribute()
    public indentity: string;

    @IsNotEmpty()
    @attribute()
    public typographic: string;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public timelinePdf: string;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public veiclePdf: string;
}