import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('googleResult')
export class GoogleResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @attribute()
    public results: object[];

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}