import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty, IsArray } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('infocrimResult')
export class InfocrimResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @IsArray()
    @attribute()
    public results: {
        elab: string,
        occurrence: string,
        type: string,
        nature: string,
        author: string,
        victim: string,
        representative: string,
        resume: string,
    }[];

    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}