import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty, IsOptional } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('infosegResult')
export class InfosegResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public receitaFederalPf: object;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public denatranRenach: object;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public mteRaisTrabalhador: object;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public cnjBnmp: object;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public sinespIntegracaoBo: object;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public receitaFederalPj: object;

    @IsOptional()
    @IsNotEmpty()
    @attribute()
    public dpfSinarm: object;

    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}