import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsEmail, IsNotEmpty, IsNumber } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('people')
export class Person {
    @autoGeneratedHashKey()
    public personId: string;

    @IsNotEmpty()
    @attribute()
    public firstName: string;

    @IsNotEmpty()
    @attribute()
    public lastName: string;

    @IsNotEmpty()
    @IsEmail()
    @attribute()
    public email: string;

    @IsNotEmpty()
    @attribute()
    public address: string;

    @IsNotEmpty()
    @attribute()
    public uidCreated: string;

    @IsNotEmpty()
    @attribute()
    public rg: string;

    @IsNotEmpty()
    @attribute()
    public cpf: string;

    @IsNotEmpty()
    @IsNumber()
    @attribute()
    public searchPages: number;

    @IsNotEmpty()
    @attribute()
    public phoneNumber: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}