import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('sielResult')
export class SielResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @attribute()
    public name: string;

    @IsNotEmpty()
    @attribute()
    public title: string;

    @IsNotEmpty()
    @attribute()
    public birthDate: string;

    @IsNotEmpty()
    @attribute()
    public zone: string;

    @IsNotEmpty()
    @attribute()
    public address: string;

    @IsNotEmpty()
    @attribute()
    public county: string;

    @IsNotEmpty()
    @attribute()
    public uF: string;

    @IsNotEmpty()
    @attribute()
    public homeDate: string;

    @IsNotEmpty()
    @attribute()
    public fatherName: string;

    @IsNotEmpty()
    @attribute()
    public motherName: string;

    @IsNotEmpty()
    @attribute()
    public naturalness: string;

    @IsNotEmpty()
    @attribute()
    public validationCode: string;

    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}