import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('sivecResult')
export class SivecResult {
    @autoGeneratedHashKey()
    public searchid: string;

    @IsNotEmpty()
    @attribute()
    public name: string;

    @IsNotEmpty()
    @attribute()
    public gender: string;

    @IsNotEmpty()
    @attribute()
    public birthday: string;

    @IsNotEmpty()
    @attribute()
    public rg: string;

    @IsNotEmpty()
    @attribute()
    public vecControlNumber: string;

    @IsNotEmpty()
    @attribute()
    public rgType: string;

    @IsNotEmpty()
    @attribute()
    public rgIssueDate: string;

    @IsNotEmpty()
    @attribute()
    public nickname: string;

    @IsNotEmpty()
    @attribute()
    public maritalStatus: string;

    @IsNotEmpty()
    @attribute()
    public naturalness: string;

    @IsNotEmpty()
    @attribute()
    public naturalnessSn: string;

    @IsNotEmpty()
    @attribute()
    public identificationStation: string;

    @IsNotEmpty()
    @attribute()
    public literacy: string;

    @IsNotEmpty()
    @attribute()
    public fundamentalFormula: string;

    @IsNotEmpty()
    @attribute()
    public fathersName: string;

    @IsNotEmpty()
    @attribute()
    public eyesColor: string;

    @IsNotEmpty()
    @attribute()
    public mothersName: string;

    @IsNotEmpty()
    @attribute()
    public hair: string;

    @IsNotEmpty()
    @attribute()
    public occupation: string;

    @IsNotEmpty()
    @attribute()
    public skinColor: string;

    @IsNotEmpty()
    @attribute()
    public address: string;

    @IsNotEmpty()
    @attribute()
    public workplace: string;

    @IsNotEmpty()
    @attribute()
    public personId: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;
}