import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsNotEmpty } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('tweets')
export class Tweets {
    @autoGeneratedHashKey()
    public tweetId: string;

    @IsNotEmpty()
    @attribute()
    public userid: string;

    @IsNotEmpty()
    @attribute()
    public text: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;

}