import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';
import { IsEmail, IsNotEmpty } from 'class-validator';
import * as Moment from 'moment-timezone';

@table('users')
export class User {
    @autoGeneratedHashKey()
    public userId: string;

    @IsNotEmpty()
    @attribute()
    public firstName: string;

    @IsNotEmpty()
    @attribute()
    public lastName: string;

    @IsNotEmpty()
    @IsEmail()
    @attribute()
    public email: string;

    @IsNotEmpty()
    @attribute()
    public address: string;

    @IsNotEmpty()
    @attribute()
    public type: string;

    @IsNotEmpty()
    @attribute()
    public uidCreated: string;

    @IsNotEmpty()
    @attribute()
    public rg: string;

    @IsNotEmpty()
    @attribute()
    public cpf: string;

    @IsNotEmpty()
    @attribute()
    public phoneNumber: string;

    @attribute({
        defaultProvider: () =>
            Moment()
                .tz('America/Sao_Paulo')
                .valueOf(),
    })
    public createdAt: number;

}