service:
  name: am-serverless

plugins:
  - serverless-webpack
  - serverless-layers

package:
  individually: false
  exclude:
    - node_modules/**
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  role:
    Fn::ImportValue: functionRoleArn-${self:custom.stage}
  deploymentBucket:
    name: am-serverless-bucket-${self:custom.stage}
  environment: ${file(./conf/env.yml):${self:custom.stage}}

custom:
  stage: ${env:SLS_STAGE, opt:stage, self:provider.stage}

functions:
  scraperEscavador:
    handler: src/handlers/scrapers/scraperEscavador.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:57
    memorySize: 1156
    timeout: 30
    events:
      - sns: search
  scraperConsultaSocio:
    handler: src/handlers/scrapers/scraperConsultaSocio.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:57
    memorySize: 1156
    timeout: 30
    events:
      - sns: search
  scraperMaps:
    handler: src/handlers/scrapers/scraperMaps.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:57
    memorySize: 1156
    timeout: 30
    events:
      - sns: search
  scraperGoogle:
    handler: src/handlers/scrapers/scraperGoogle.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:57
    memorySize: 1156
    timeout: 30
    events:
      - sns: search
  scraperJucesp:
    handler: src/handlers/scrapers/scraperJucesp.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:57
    memorySize: 1156
    timeout: 30
    events:
      - sns: search
  scraperSivec:
    handler: src/handlers/scrapers/scraperSivec.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:57
    memorySize: 1156
    timeout: 30
    events:
      - sns: search
  # scraperFacebook:
  #   handler: src/handlers/scrapers/scraperFacebook.handler
  #   layers: 
  #     - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:57
  #   memorySize: 1156
  #   timeout: 30
  #   events:
  #     - sns: search
  createPerson:
    handler: src/handlers/create/createPerson.handler
    events:
      - http:
          method: post
          path: person
          cors: true
  getPeople:
    handler: src/handlers/read/getPeople.handler
    events:
      - http:
          method: get
          path: person
          cors: true
  # generateReport:
  #   handler: src/handlers/read/generateReport.handler
  #   events:
  #     - http:
  #         method: get
  #         path: person/{personId}/report
  #         cors: true

