service:
  name: am-serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  role:
    Fn::ImportValue: functionRoleArn-${self:custom.stage}
  deploymentBucket:
    name: am-serverless-bucket-${self:custom.stage}

custom:
  stage: ${env:SLS_STAGE, opt:stage, self:provider.stage}

functions:
  getTweets:
    handler: src/handlers/getTweets.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:46
    memorySize: 1156
    timeout: 20
    events:
      - http:
          path: tweets
          method: get
          cors: true

