service:
  name: am-serverless

plugins:
  - serverless-webpack
  - serverless-layers

package:
  individually: false
  exclude:
    - node_modules/**
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  role:
    Fn::ImportValue: functionRoleArn-${self:custom.stage}
  deploymentBucket:
    name: am-serverless-bucket-${self:custom.stage}
  environment: ${file(./conf/env.yml):${self:custom.stage}}

custom:
  stage: ${env:SLS_STAGE, opt:stage, self:provider.stage}

functions:
  # scraperEscavador:
  #   handler: src/handlers/scrapers/scraperEscavador.handler
  #   layers: 
  #     - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:53
  #   memorySize: 1156
  #   timeout: 30
  #   events:
  #     - sns: search
  # scraperConsultaSocio:
  #   handler: src/handlers/scrapers/scraperConsultaSocio.handler
  #   layers: 
  #     - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:53
  #   memorySize: 1156
  #   timeout: 30
  #   events:
  #     - sns: search
  scraperMaps:
    handler: src/handlers/scrapers/scraperMaps.handler
    layers: 
      - arn:aws:lambda:us-east-1:770168723546:layer:ChromiumSelenium:53
    memorySize: 1156
    timeout: 30
    events:
      - sns: search
  createPerson:
    handler: src/handlers/create/createPerson.handler
    events:
      - http:
          method: post
          path: person
          cors: true

